// testing-cs.zip/svelte-app/src/lib/Test4.svelte
<!-- filename: src/components/UserDashboard.svelte -->
<script lang="ts">
  import { onMount } from 'svelte';

  let userName: string = 'Guest';
  let notificationCount: number = 0;
  let showDetails: boolean = false;
  let lastUpdate: string = '';
  let expensiveCalculationResult: string = '';

  const MAX_NOTIFICATIONS = 10;

  function performExpensiveCalculation(multiplier: number): string {
    console.log("Performing expensive calculation in Svelte...");
    let result = 0;
    for (let i = 0; i < 10000 * multiplier; i++) {
      result += Math.sin(i) * Math.cos(i);
    }
    return `Result: ${result.toFixed(2)}`;
  }

  function handleLogin(user: string) {
    userName = user;
    lastUpdate = new Date().toLocaleTimeString();
    console.log(`${user} logged in at ${lastUpdate}`);
  }

  function toggleDetails() {
    showDetails = !showDetails;
    lastUpdate = new Date().toLocaleTimeString();
  }

  onMount(() => {
    userName = 'Alice';
    notificationCount = 3;
    lastUpdate = new Date().toLocaleTimeString();
    expensiveCalculationResult = performExpensiveCalculation(1);
  });

  $: if (notificationCount > 0) {
    console.log(`New notifications: ${notificationCount}`);
  }

  function getSystemStatus(): string {
    console.log("Getting system status...");
    const currentHour = new Date().getHours();
    return currentHour > 8 && currentHour < 18 ? 'Operational' : 'Maintenance Window';
  }
</script>

<div class="dashboard-container">
  <h1>Welcome, {userName}!</h1>
  <p>Last updated: {lastUpdate}</p>

  <div class="header-actions">
    <button on:click={() => (notificationCount = Math.min(notificationCount + 1, MAX_NOTIFICATIONS))}>
      Add Notification
    </button>
    <button on:click={() => handleLogin('Bob')}>
      Login as Bob
    </button>
    <button on:click={toggleDetails}>
      {showDetails ? 'Hide' : 'Show'} Details
    </button>
  </div>

  <div class="status-widgets">
    <div class="widget">
      <h3>Notifications</h3>
      <p class:has-notifications={notificationCount > 0}>
        You have {notificationCount} new {notificationCount === 1 ? 'notification' : 'notifications'}.
      </p>
    </div>

    <div class="widget">
      <h3>System Status</h3>
      <p>Status: {getSystemStatus()}</p>
    </div>
  </div>

  {#if showDetails}
    <div class="detailed-info">
      <h3>Detailed Information</h3>
      <p>Here are some more in-depth metrics and controls.</p>
      <p>Complex Data Point: {performExpensiveCalculation(2)}</p>
      <button on:click={() => alert('Feature X clicked!')}>Activate Feature X</button>
    </div>
  {/if}
</div>

<style>
  .dashboard-container {
    max-width: 800px;
    margin: 30px auto;
    padding: 25px;
    border-radius: 10px;
    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
    background-color: #f8f9fa;
    font-family: Arial, sans-serif;
  }
  h1 {
    color: #343a40;
    margin-bottom: 20px;
  }
  p {
    color: #6c757d;
    line-height: 1.6;
  }
  .header-actions button {
    background-color: #007bff;
    color: white;
    border: none;
    padding: 10px 18px;
    margin-right: 10px;
    border-radius: 5px;
    cursor: pointer;
    font-size: 0.95rem;
    transition: background-color 0.3s ease;
  }
  .header-actions button:hover {
    background-color: #0056b3;
  }
  .status-widgets {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 20px;
    margin-top: 25px;
  }
  .widget {
    background-color: #ffffff;
    border: 1px solid #e9ecef;
    border-radius: 8px;
    padding: 20px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
  }
  .widget h3 {
    color: #495057;
    margin-bottom: 10px;
  }
  .has-notifications {
    font-weight: bold;
    color: #dc3545;
  }
  .detailed-info {
    margin-top: 30px;
    padding: 25px;
    border: 1px dashed #28a745;
    border-radius: 8px;
    background-color: #e6ffed;
  }
</style>

// testing-cs.zip/vue-app/src/components/Test4.vue
<template>
  <div class="complex-feature-container">
    <h2>Detailed Analytics Dashboard</h2>
    <p>Explore in-depth metrics and user behavior patterns.</p>

    <div class="controls">
      <button @click="loadLargeDataSet">Load Extensive Data</button>
      <button @click="showAdvancedChart = !showAdvancedChart">
        {{ showAdvancedChart ? 'Hide' : 'Show' }} Advanced Chart Options
      </button>
    </div>

    <div v-if="showAdvancedChart" class="advanced-chart-section">
      <h3>Advanced User Journey Chart</h3>
      <p>This chart provides highly granular data that is not always needed.</p>
      <div class="chart-placeholder">
        <p>Rendering very detailed chart...</p>
        <p>{{ getChartInitializationStatus() }}</p>
      </div>
      <button @click="exportChart">Export Chart Data (CSV)</button>
    </div>

    <div v-else class="simple-view">
      <h3>Basic Overview</h3>
      <p>Click "Show Advanced Chart Options" for more detailed visualizations.</p>
    </div>

    <hr>

    <div class="data-display">
      <h4>Current Data Metrics</h4>
      <ul>
        <li v-for="item in processedData" :key="item.id">
          {{ item.name }}: {{ item.value }} (Processed: {{ item.processed }})
        </li>
      </ul>
      <p v-if="processedData.length === 0">No data loaded yet.</p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from 'vue';
import _ from 'lodash';

interface DataItem {
  id: number;
  name: string;
  value: number;
}

export default defineComponent({
  name: 'ComplexFeaturePage',
  setup() {
    const showAdvancedChart = ref(false);
    const rawData = ref<DataItem[]>([]);

    const loadLargeDataSet = () => {
      rawData.value = Array.from({ length: 500 }, (_, i) => ({
        id: i,
        name: `Metric ${i + 1}`,
        value: Math.floor(Math.random() * 1000)
      }));
      console.log('Extensive data loaded:', rawData.value.length, 'items');
    };

    const processedData = computed(() => {
      if (rawData.value.length === 0) return [];
      return _.shuffle(rawData.value).slice(0, 10).map(item => ({
        ...item,
        processed: item.value * 2
      }));
    });

    const getChartInitializationStatus = () => {
      let status = "Initializing complex chart... ";
      for (let i = 0; i < 50000; i++) {
        Math.pow(Math.sin(i / 100), 2);
      }
      return status + "Done!";
    };

    const exportChart = () => {
      alert('Exporting chart data...');
      console.log('Exporting data for items:', _.map(processedData.value, 'id').join(', '));
    };

    return {
      showAdvancedChart,
      rawData,
      loadLargeDataSet,
      processedData,
      getChartInitializationStatus,
      exportChart
    };
  }
});
</script>

<style scoped>
.complex-feature-container {
  max-width: 900px;
  margin: 40px auto;
  padding: 30px;
  border-radius: 12px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.1);
  background-color: #ffffff;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}

h2, h3, h4 {
  color: #2c3e50;
  margin-bottom: 15px;
}

.controls button {
  background-color: #42b983;
  color: white;
  border: none;
  padding: 10px 20px;
  margin-right: 15px;
  border-radius: 6px;
  cursor: pointer;
  font-size: 1rem;
  transition: background-color 0.3s ease;
}

.controls button:hover {
  background-color: #368a6f;
}

.advanced-chart-section {
  margin-top: 30px;
  padding: 25px;
  border: 1px dashed #42b983;
  border-radius: 8px;
  background-color: #f0fff4;
}

.simple-view {
  margin-top: 30px;
  padding: 20px;
  background-color: #f9f9f9;
  border-radius: 8px;
  border: 1px solid #eee;
}

.chart-placeholder {
  height: 300px;
  background-color: #e6f7ed;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  border-radius: 6px;
  margin-top: 20px;
  color: #28a745;
  font-style: italic;
}

.data-display ul {
  list-style-type: none;
  padding: 0;
  margin-top: 20px;
}

.data-display li {
  background-color: #f7f9fb;
  border: 1px solid #e0e6ed;
  padding: 10px 15px;
  margin-bottom: 8px;
  border-radius: 4px;
}
</style>
